"use client"

// Workspace AI tools (FUTURE): daily standup + changelog from merged PRs.
// Calls /api/ai/standup and /api/ai/changelog, renders the markdown result.

import { useState } from "react"
import { Sparkles, Loader2, Newspaper } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { AiFeedback } from "@/components/ai/ai-feedback"

export function AiInsights({ workspaceId }: { workspaceId: string }) {
  const [open, setOpen] = useState(false)
  const [title, setTitle] = useState("")
  const [body, setBody] = useState("")
  const [feature, setFeature] = useState<"standup" | "changelog">("standup")
  const [traceId, setTraceId] = useState<string | undefined>()
  const [loading, setLoading] = useState<null | "standup" | "changelog">(null)

  async function run(kind: "standup" | "changelog") {
    setLoading(kind)
    setBody("")
    setTraceId(undefined)
    setFeature(kind)
    setTitle(kind === "standup" ? "Daily standup" : "Changelog")
    setOpen(true)
    try {
      const url = kind === "standup" ? "/api/ai/standup" : "/api/ai/changelog"
      const payload = kind === "standup" ? { workspaceId } : { wsId: workspaceId }
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })
      const data = await res.json()
      if (!res.ok) {
        toast.error(data.error ?? "Failed")
        setOpen(false)
        return
      }
      setBody(kind === "standup" ? data.digest : data.changelog)
      setTraceId(data.traceId)
    } finally {
      setLoading(null)
    }
  }

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="sm" className="gap-1.5" disabled={!!loading} onClick={() => run("standup")}>
        {loading === "standup" ? <Loader2 className="size-4 animate-spin" /> : <Sparkles className="size-4" />}
        AI standup
      </Button>
      <Button variant="outline" size="sm" className="gap-1.5" disabled={!!loading} onClick={() => run("changelog")}>
        {loading === "changelog" ? <Loader2 className="size-4 animate-spin" /> : <Newspaper className="size-4" />}
        Changelog
      </Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="max-h-[75vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Sparkles className="size-4" /> {title}
            </DialogTitle>
            <DialogDescription>Generated by Claude from this workspace&apos;s activity.</DialogDescription>
          </DialogHeader>
          {loading ? (
            <p className="text-muted-foreground py-8 text-center text-sm">Generating…</p>
          ) : (
            <>
              <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">{body}</pre>
              {traceId && <AiFeedback className="mt-3" traceId={traceId} feature={feature} workspaceId={workspaceId} />}
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  )
}
